### ISSUE TITLE
Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

### ISSUE THREAD

**Issue by gabrielecastellano** [sunilpulugula/SpringSecuritySocialLoginExample#1]
Hi, i get this error while deploying.
the hibernate.dialect property is set in database.property file.
What i'm missing?

**Comment by sunilpulugula** [comment]
Issue is addressed by adding hibernate dialect property in LocalSessionFactoryBean.Plese pull latest changes and validate your scenario.
