### ISSUE TITLE
email is missing in UserProfile got by all providers

### ISSUE THREAD

**Issue by Jan-Kuta** [sunilpulugula/SpringSecuritySocialLoginExample#2]
Hello,
first of all, thank you very much for sharing  this project. It is exactly thing I am looking for. Good job.
I have problems with social login (by all providers). In UserProfile, which is returned by provider, the email is missing (So new account is not created and error 500 is thrown, because email is mandatory for User). I found in some forums, that it could be by bad scope, but I think that it is not the problem, because for example by Facebook provider there is explicitely said that you want email scope.
Do you know what am I doing wrong?
Thank you in advance,
Honza

**Comment by sunilpulugula** [comment]
Hi, Even I use to get email Id from Face book provider earlier.It seems in FB 2.0 applications, they are not providing email ids.For now I updated nullable to true for email property in user object.I see for other providers like linkedin,twitter we are getting email id value.
